/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Solver_CPPSimulator */

#ifndef _Included_Solver_CPPSimulator
#define _Included_Solver_CPPSimulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Solver_CPPSimulator
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Solver_CPPSimulator_init
  (JNIEnv *, jclass);

/*
 * Class:     Solver_CPPSimulator
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Solver_CPPSimulator_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Solver_CPPSimulator
 * Method:    getHeight
 * Signature: (IIJ)F
 */
JNIEXPORT jfloat JNICALL Java_Solver_CPPSimulator_getHeight
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     Solver_CPPSimulator
 * Method:    getBathymetry
 * Signature: (IIJ)F
 */
JNIEXPORT jfloat JNICALL Java_Solver_CPPSimulator_getBathymetry
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     Solver_CPPSimulator
 * Method:    simulatetimestep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Solver_CPPSimulator_simulatetimestep
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
